%%%Comparing Mass for similar sized fish in and out of preserve
%%%Some Necessary data for this code to run is generated by
%%%IndividualDetectionStatistics. Run the latest version of
%%%IndividualDetectionStatistics before running this script.

tic

run (IndividualDetectionStatistics_V_1_0.m);

%%compare mass value to length
%%look at general trend for all individuals
%%determine if fish in BARF are larger than those outside

%%%Pull out master sheet file to get meta data.

%%Mass not currently recorded for individuals. In the future this should 
%%be done. Until then, all lines running code with mass have been dissabled

%%Notes on BottomFish
%%Column 1=Tag ID
%%Column 2=Date&Time
%%Column 3=Zeros (By end of this script this indicates spent more or less
    %%time in BAFR
%%Column 4=Reciever ID
%%Column 5=Location of Reciever (1=Barber Flats, 2=Diamond Head, 3=Kaena
    %%Pocket, 4=Kahuku, 5=Ko Olina, 6=Makapuu[in BAFR],7=Makapuu S[Out of
    %%BAFR], 8=Makapuu N, 9=Mokapu, 10=Powerplant, 11=Waianae)
%%Column 6 =Presence in BAFR or out of BAFR.
    %%1 indicates individual detected in BAFR, 0 indicates detection outside
    %%BAFR
%%Column 7=Species (1=Ehu, 2=Opaka, 3=Dogfish, 4=Ges, 5=Kale, 6=Sandbar



Tags=unique(BottomFish(:,1));


%%adding Sex, Mass, and Length features to the BottomFish variable
Sex=NaN(length(BottomFish),1);
%%Mass=NaN(length(BottomFish),1);
Length=NaN(length(BottomFish),1);
BottomFish=[BottomFish, Length, Sex];


%%pulling meta data from masterfile into bottomfish
for i=1:length(Tags);
    IndvMetaData=MasterFile(MasterFile(:,8)==Tags(i),:);
    Sex(i)=IndvMetaData(:,23);
    %%%%Mass(i)=IndvMetaData(:,  %%%%Mass Data Unavailable right now. Get it in the future and add to this
    Length(i)=IndvMetaData(:,9); %%%%Length Data Unavailable right now. Get it in the future and add to this
end

     
BottomFish(:,9)=Sex;
%%BottomFish(:,9)=Mass;
BottomFish(:,8)=Length;

clearvars i IndvMetaData 

%% Changng BottomFish Column 3 to reflect if fish spends more time in our out of BAFR

Bottomfish(BottomFish(:,3)==0,3)=NaN;

if length(BottomFish)==length(StateChangeStatisticsByTagID) %%determines that the matrix BottomFish is the same length as the matrix StateChangeStatsisticsByID output by IndividualDetectionStatistics
    for i=1:length(Tags) 
        if StateChangeStatisticsByTagID(i,3)>.5  %%StateChangeStatisticsByID(:,3) shows time in BAFR as a fraction of total time. Values greater than .5 indicate that an individual spends more time in the BAFR than out
            BottomFish(:,3)=1; %%Individuals that spend more time in BAFR tagged 1
        elseif StateChangeStatisticsByTagID(i,3)<.5
            BottomFish(:,3)=0; %%Individuals that spend more time out of BAFR tagged 0
        elseif StateChangeStatisticsByTagID(i,3)==.5
            disp 'somehow there is an individual that spends exactly half their time in and out'
        end
    end
end

%%%Comparing individuals from the BAFR to individuals out

IndividualsIn=BottomFish(BottomFish(:,3)==1,:);
IndividualsOut=BottomFish(BottomFish(:,3)==0,:);

MeanLengthIn=sum(IndividualsIn(:,8))/length(IndividualsIn);
MeanLengthOut=sum(IndividualsOut(:,8))/length(IndividualsOut);

%MeanMassIn=sum(IndividualsIn(:,9))/length(IndividualsIn);
%MeanMassOut=sum(IndividualsOut(:,9))/length(IndividualsOut);



