%%%Some Necessary data for this code to run is generated by
%%%IndividualDetectionStatistics. Run the latest version of
%%%IndividualDetectionStatistics before running this script.

%Updates in V_1_0
%Code updated to rely on WorkingDatabaseForAllCode     

tic

run (IndividualDetectionStatistics_V_1_0.m);

%%compare mass value to length
%%look at general trend for all individuals
%%determine if fish in BARF are larger than those outside

%%%Pull out master sheet file to get meta data.

%%Mass not currently recorded for individuals. In the future this should 
%%be done. Until then, all lines running code with mass have been dissabled

%%Notes on BottomFish
    %%Column 1=Tag ID
    %%Column 2=Date&Time
    %%Column 3=Reciever ID(1=Barber Flats, 2=Base3rdFinger, 3=Diamond Head
        %%Pocket, 4=Dropoff Inside, 5=First Finger, 6=Haleiwa,7=Kaena Pocket,
        %%8=Kahuku, 9=Makapuu In BFRA, 10=Makapuu North, 11=Makapuu South,
        %%12=Marine Corps Base, 13=Pinnacle South, 14=Powerplant, 
        %%15=South of Ko Olina,16=South Tip, 17=SWAC, 18=The Mound, 19=Waianae,
        %%20=Cross Seamount, 21=Botcam Crew)
    %%Column 5=Species (1=Ehu, 2=Opaka, 3=Dogfish, 4=Ges, 5=Kale, 6=Sandbar, 0=unknown)
    %%Column 6=Size (cm)
    %%Column 7=Sex (1=Female, 2=Male, 0=Unknown)
    %%Column 8=(Created in following section)=Presence in BRFA or out of BRFA.
        %%1 indicates individual detected in BAFR, 0 indicates detection outside
        %%BRFA



Tags=unique(BottomFish(:,1));

%% Changng BottomFish Column 3 to reflect if fish spends more time in our out of BAFR

Addendum=nan(length(BottomFish),1);
BottomFish=[BottomFish,Addendum];
clear Addendum

if length(Tags)==length(StateChangeStatisticsByTagID) %%determines that the matrix Tags is the same length as the matrix StateChangeStatsisticsByID output by IndividualDetectionStatistics
    for i=1:length(Tags);
        if StateChangeStatisticsByTagID(i,3)>.5  %%StateChangeStatisticsByID(:,3) shows time in BAFR as a fraction of total time. Values greater than .5 indicate that an individual spends more time in the BAFR than out
            BottomFish(:,9)=1; %%Individuals that spend more time in BAFR tagged 1
        elseif StateChangeStatisticsByTagID(i,3)<.5
            BottomFish(:,9)=0; %%Individuals that spend more time out of BAFR tagged 0
        elseif StateChangeStatisticsByTagID(i,3)==.5
            disp 'somehow there is an individual that spends exactly half their time in and out'
        end
    end
end

%%%Comparing size of individuals from the BAFR to individuals out

IndividualsIn=BottomFish(BottomFish(:,9)==1,:);
IndividualsOut=BottomFish(BottomFish(:,9)==0,:);

MeanLengthIn=sum(IndividualsIn(:,6))/length(IndividualsIn);
MeanLengthOut=sum(IndividualsOut(:,6))/length(IndividualsOut);

%MeanMassIn=sum(IndividualsIn(:,9))/length(IndividualsIn);
%MeanMassOut=sum(IndividualsOut(:,9))/length(IndividualsOut);

%%%%StatsTime!
nIn=length(IndividualsIn);
meanIn=sum(IndividualsIn(:,6))/nIn;
standarddeviationIn=std(meanIn);

nOut=length(IndividualsOut);
meanOut=sum(IndividualsOut(:,6))/nOut;
standarddeviationOut=std(meanOut);





